project:
  type: website

website:
  title: "New Ways of Academic Publishing Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: introduction.qmd
        text: Why and How?
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# Additional extensions for Sphinx
sphinx:
  config:
    suppress_warnings: ["mystnb.unknown_mime_type"]
    html_copy_source: false
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js
  extra_extensions:
    - sphinxcontrib.mermaid # Draw diagrams with Mermaid