project:
  type: website

website:
  title: "New Ways of Academic Publishing Workshop"
  site-url: https://intelligentsystemslaboratory.github.io/nwoap_workshop/
  repo-url: https://github.com/IntelligentSystemsLaboratory/nwoap_workshop
  repo-branch: main
  repo-actions: [edit, issue]
  #navbar:
  #  left:
  #    - href: index.qmd
  #      text: Home
  #    - href: introduction.qmd
  #      text: Why and How?
  #    - href: IAIhub.qmd
  #      text: 'IAI Hub'
  #    - href: jekyll.qmd
  #      text: 'Jekyll'
  #    - quarto.qmd
  #    - about.qmd
  sidebar:
    style: "docked"
    logo: "./images/nwoap_book_world_library_thumbnail.jpg"
    search: true
    collapse-level: 2
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/IntelligentSystemsLaboratory/nwoap_workshop
          - text: Report a Bug
            href: https://github.com/IntelligentSystemsLaboratory/nwoap_workshop/issues/new?labels=bug
    contents:
      - href: index.qmd
        text: Home
      - href: introduction.qmd
        text: Why and How?
      - IAIhub.qmd
      - href: jekyll.qmd
        text: 'Jekyll'
      - quarto.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mermaid:
      theme: neutral

# Additional extensions for Sphinx
sphinx:
  config:
    suppress_warnings: ["mystnb.unknown_mime_type"]
    html_copy_source: false
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js
  extra_extensions:
    - sphinxcontrib.mermaid # Draw diagrams with Mermaid
